services:
  healthify-backend:
    depends_on:
      - mongodb
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - log-data:/app/logs

volumes:
  log-data:
    name: log-data
    driver: local